### ISSUE TITLE
Performance bug: Data generation significantly slows down test execution

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#35]
Reproduction steps:
* Create environment with following content:
```
{
  "defaultVariables" : {
  },
  "environments" : {
    "Generated" : {
      "data" : "{{dataGenerator().name().suffix()}}",
      "data2" : "{{dataGenerator().name().suffix()}}",
      "data3" : "{{dataGenerator().name().suffix()}}",
      "data4" : "{{dataGenerator().name().suffix()}}",
      "data5" : "{{dataGenerator().name().suffix()}}"
    }
  }
}
```
* Copy the [Test.txt] file to the project and rename it to Test.test.
* Select the "Generated" environment and try to run the test.
Notice how the number of dataGenerator usages in the test environment settings affect the performance of the test runs.

When checking what's going on using jstack, the following stacktrace can be seen often:
```
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:466)
	at com.github.javafaker.service.FakeValuesService.fakerFromStream(FakeValuesService.java:99)
	at com.github.javafaker.service.FakeValuesService.<init>(FakeValuesService.java:67)
	at com.github.javafaker.Faker.<init>(Faker.java:100)
	at com.github.javafaker.Faker.<init>(Faker.java:91)
	at com.github.javafaker.Faker.<init>(Faker.java:87)
	at com.testerum.common.expression_evaluator.helpers.impl.DataGeneratorScriptingHelper$DataGenerator.call(DataGeneratorScriptingHelper.kt:20)
	at com.testerum.common.nashorn.JsFunction.call(JsFunction.kt:14)
```

Looks like DataGeneratorScriptingHelper creates a new instance of Faker each time, and the Faker instance ends up loading a YAML resource, and parsing it on each occasion, slowing the overall test execution down.

The Faker instance should be probably a singleton, and it should be probably also considered to update the Faker library, as it seems to be quite out of date currently.

[Test.txt]: https://github.com/testerum/testerum/files/5669308/Test.txt

**Comment by ionut-pruteanu** [comment]
This is a very nice observation. Thank you for digging so deep. We will fix it.
