### ISSUE TITLE
Documentation bug: matchesRegex documentation should use single quotes

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#37]
When trying to use "Then the HTTP response should be `<<httpResponseVerify>>`" step, with the following JSON Verify value:
```
{
  "name": "@matchesRegex(\".*\")"
}
```
The test will fail with a stacktrace:
```
@matchesRegex(".*")
              ^--- ERROR at line 1, column 15: [null, false, true, integer, ' or )] expected, ["] encountered 

com.testerum.common.parsing.executer.ParserExecuterException: failed to parse:
@matchesRegex(".*")
              ^--- ERROR at line 1, column 15: [null, false, true, integer, ' or )] expected, ["] encountered
	at com.testerum.common.parsing.executer.ParserExecuter.parse(ParserExecuter.kt:43)
	at com.testerum.common_assertion_functions.evaluator.FunctionEvaluator.evaluate(FunctionEvaluator.kt:18)
```
This is because FunctionCallParserFactory actually uses single quotes in textFunctionArg() instead of double quotes. The documentation should be updated to this effect and the extra note about escaping the double quotes should be removed.

**Comment by aldaris** [comment]
Link to the affected doc: https://testerum.com/documentation/ui/http/
