### ISSUE TITLE
Bug: log all variables causes test failure

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#46]
Steps to reproduce:

Create a new test
Add a new "When I log all the variables" test step to the test
Run test
Note: how the test fails 

Details:
- Linux
- v5.0.2
- Chrome 87.0.4280.141

Log of error
````
Finished executing step [BASIC: WHEN I log all the variables]; status: [FAILED]

empty stack 

java.lang.RuntimeException: empty stack
	at com.testerum.runner_cmdline.runner_tree.vars_context.ArgsContext.currentLevel(ArgsContext.kt:11)
	at com.testerum.runner_cmdline.runner_tree.vars_context.ArgsContext.getKeys(ArgsContext.kt:31)
	at com.testerum.runner_cmdline.runner_tree.vars_context.VariablesContext.getAllKeys(VariablesContext.kt:193)
	at com.testerum.runner_cmdline.runner_tree.vars_context.VariablesContext.toMap(VariablesContext.kt:180)
	at com.testerum.runner_cmdline.runner_tree.vars_context.VariablesContext.getVariablesDetailsForDebugging(VariablesContext.kt:175)
	at com.testerum.runner_cmdline.runner_api_services.TestVariablesImpl.getVariablesDetailsForDebugging(TestVariablesImpl.kt:29)
	at debug.DebugSteps.logVariables(DebugSteps.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.testerum.runner_cmdline.runner_tree.nodes.step.impl.RunnerBasicStep.doRun(RunnerBasicStep.kt:68)
	at com.testerum.runner_cmdline.runner_tree.nodes.step.RunnerStep.execute(RunnerStep.kt:40)
	at com.testerum.runner_cmdline.runner_tree.nodes.test.RunnerTest.runChildren(RunnerTest.kt:135)
	at com.testerum.runner_cmdline.runner_tree.nodes.test.RunnerTest.tryToRun(RunnerTest.kt:89)
	at com.testerum.runner_cmdline.runner_tree.nodes.test.RunnerTest.execute(RunnerTest.kt:59)
	at com.testerum.runner_cmdline.runner_tree.nodes.feature.RunnerFeature.runChildren(RunnerFeature.kt:116)
	at com.testerum.runner_cmdline.runner_tree.nodes.feature.RunnerFeature.tryToRun(RunnerFeature.kt:84)
	at com.testerum.runner_cmdline.runner_tree.nodes.feature.RunnerFeature.execute(RunnerFeature.kt:63)
	at com.testerum.runner_cmdline.runner_tree.nodes.suite.RunnerSuite.runChildren(RunnerSuite.kt:104)
	at com.testerum.runner_cmdline.runner_tree.nodes.suite.RunnerSuite.execute(RunnerSuite.kt:70)
	at com.testerum.runner_cmdline.RunnerApplication$tryToExecute$executionStatus$1.invoke(RunnerApplication.kt:142)
	at com.testerum.runner_cmdline.RunnerApplication$tryToExecute$executionStatus$1.invoke(RunnerApplication.kt:41)
	at com.testerum.common_kotlin.Classloader_utilsKt.runWithThreadContextClassLoader(classloader_utils.kt:8)
	at com.testerum.runner_cmdline.RunnerApplication.tryToExecute(RunnerApplication.kt:141)
	at com.testerum.runner_cmdline.RunnerApplication.execute(RunnerApplication.kt:62)
	at com.testerum.runner_cmdline.TesterumRunner.main(TesterumRunner.kt:39)
````

**Comment by ionut-pruteanu** [comment]
Hi Ajhad,
Thank you for reporting this issues.
This is a big bug, we will fix it with priority. Will be available in the next release.

Regards,
Ionut

**Comment by Ajhad1** [comment]
Sounds great. Thank you.

**Comment by ionut-pruteanu** [comment]
This issue is fixed, will be available in the next release

**Comment by aldaris** [comment]
Thanks, it works as expected in version 5.0.5. Feel free to close out this issue.
