### ISSUE TITLE
Bug Report: Run Config that does not match any tests generates error

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#47]
When a run configuration does not match any tests, all of the tests run anyway. 
Sometimes, an error is generated when this happens and the UI stops working correctly. Other times, there is no error at all. In both cases, all of the tests run. 
Below are 2 ways to replicate the issue.

Steps to Reproduce the behavior **without** the error message:
Go to a project with any tests
Create a run configuration but do not change any of the settings
Run the run configuration
All tests will run anyway

Steps to Reproduce the behavior **with** the error message:
Create a project with 1 test
Add a tag to the test
Create a run configuration that excludes the only tag
Run the run configuration
The test will run anyway 

Error Generated:
```
Error Message:
cannot find Runner tree node for event key [TestSuite_0#Test Feature/info.feat_0#]
availableKeys=[
]

Error StackTrace:
Error: cannot find Runner tree node for event key [TestSuite_0#Test Feature/info.feat_0#]
availableKeys=[
]
    at e.getNodeByEventKey (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:5447659)
    at e.onRunnerEvent (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:5444977)
    at http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:5444165
    at d.o [as _next] (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1033595)
    at d.__tryOrUnsub (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:86701)
    at d.next (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:85922)
    at c._next (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:85093)
    at c.next (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:84867)
    at dl.next (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:667656)
    at dl.emit (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1033247)
```

**Comment by ionut-pruteanu** [comment]
Thank you reporting is issue, 
We will fix it.

**Comment by Ajhad1** [comment]
Thank you. 
Let me know if there is anything I need to provide for this one.
