### ISSUE TITLE
Bug Report: Copy and Paste step on composed steps page generates error

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#49]
Steps to reproduce:

Go to "Steps" page
Create a new composed step
Add a test step
Click the copy icon on the test step
Click the paste icon

Details:

Linux
v5.0.2

Log of Error:
```
Error Message:
is(...).onPasteStep is not a function

Error StackTrace:
TypeError: is(...).onPasteStep is not a function
    at http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:5173467
    at ns (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1001512)
    at i (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1001672)
    at HTMLDivElement. (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1109281)
    at l.invokeTask (http://localhost:8080/polyfills-es2018.5e02e5899400dc7f2ad6.js:1:19466)
    at Object.onInvokeTask (http://localhost:8080/main-es2018.741293ead61a37773c12.js:1:1043140)
    at l.invokeTask (http://localhost:8080/polyfills-es2018.5e02e5899400dc7f2ad6.js:1:19387)
    at s.runTask (http://localhost:8080/polyfills-es2018.5e02e5899400dc7f2ad6.js:1:14875)
    at u.invokeTask [as invoke] (http://localhost:8080/polyfills-es2018.5e02e5899400dc7f2ad6.js:1:20516)
    at f (http://localhost:8080/polyfills-es2018.5e02e5899400dc7f2ad6.js:1:32455)
```

**Comment by ionut-pruteanu** [comment]
Thank you for reporting this issue.
I just fixed it. Will be available in the next release
