### ISSUE TITLE
Bug: Missing report templates in 5.1.1

### ISSUE THREAD

**Issue by medavian** [testerum/testerum#61]
Hey Team,

I have upgraded to Testerum 5.1.1 and it seems there are some missing templates (or they have moved). 

When using the test runner, we get the following errors at the end of the test run when it is trying to generate a report.

```
17-Feb-2021 11:34:28 | [main.bundle.js] [app/generator] copying templates from [/opt/testerum_home/testerum/runner/report_templates/pretty/report-template] to /reports/2021-02-17/00-34-23-656/pretty
-- | --
17-Feb-2021 11:34:28 | [main.bundle.js] Error: ENOENT: no such file or directory, stat '/opt/testerum_home/testerum/runner/report_templates/pretty/report-template'
17-Feb-2021 11:34:28 | [main.bundle.js]     at Object.statSync (fs.js:1086:3)
17-Feb-2021 11:34:28 | [main.bundle.js]     at Object.this [as statSync] (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/node_modules/graceful-fs/polyfills.js:287:1)
17-Feb-2021 11:34:28 | [main.bundle.js]     at /opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/node_modules/fs-extra/lib/copy-sync/copy-sync.js:182:1
17-Feb-2021 11:34:28 | [main.bundle.js]     at p (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/node_modules/fs-extra/lib/copy-sync/copy-sync.js:176:1)
17-Feb-2021 11:34:28 | [main.bundle.js]     at Object.t.exports [as copySync] (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/node_modules/fs-extra/lib/copy-sync/copy-sync.js:21:1)
17-Feb-2021 11:34:28 | [main.bundle.js]     at Object.log [as copyTemplateFiles] (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/src/Application.ts:27:17)
17-Feb-2021 11:34:28 | [main.bundle.js]     at Object.run (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/src/Application.ts:14:25)
17-Feb-2021 11:34:28 | [main.bundle.js]     at Module.logsSrcDir (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/src/Application.ts:52:64)
17-Feb-2021 11:34:28 | [main.bundle.js]     at n (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/webpack/bootstrap:9:1)
17-Feb-2021 11:34:28 | [main.bundle.js]     at object (/opt/testerum_home/testerum/runner/report_templates/pretty/webpack:/webpack/bootstrap:76:1)
```

Let me know if there is anything else needed for this.

I have rolled back to 5.1.0 as it does not have this issue.

Kind Regards,
Darrin

**Comment by ionut-pruteanu** [comment]
Hi Darrin,

Thank you for reporting this issue. We are working currently on in and soon will be fixed.
