### ISSUE TITLE
Issue on ConnectionTimeout and HttpHeader Size in Apache server?

### ISSUE THREAD

**Issue by muhammad-asn** [testerum/testerum#78]
Hello, I've been wondering if there's a way to manually adjust the `connectionTimeout` and `maxHttpHeaderSize` in this repo configuration.
 
Currently I have a setup like this

Jobs -> Nginx (load balancer)-> Testerum Report Server

and I got this issue on Nginx side
```
 4019039#4019039: *2322980374 readv() failed (104: Connection reset by peer) while reading upstream, .....
 ```
 
 After I check on the Jobs (CI/CD), the output shows
 ```
 12:29:18.998 [main] ERROR com.testerum.runner_cmdline.module_di.submodules.RunnerListenersModuleFactory - failed to shutdown execution listener RemoteServerExecutionListener
org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:138)
	at com.testerum.common_httpclient.HttpClientService.convertResponse(HttpClientService.kt:131)
	at com.testerum.common_httpclient.HttpClientService.executeHttpRequest(HttpClientService.kt:100)
	at com.testerum.common_httpclient.HttpClientService.executeHttpRequest$default(HttpClientService.kt:41)
	at com.testerum.report_generators.reports.remote_server.RemoteServerExecutionListener.stop(RemoteServerExecutionListener.kt:98)
	at com.testerum.runner_cmdline.events.EventsService.stop(EventsService.kt:54)
	at com.testerum.runner_cmdline.module_di.RunnerModuleFactory$eventsService$1$1.invoke(RunnerModuleFactory.kt:40)
	at com.testerum.runner_cmdline.module_di.RunnerModuleFactory$eventsService$1$1.invoke(RunnerModuleFactory.kt:20)
	at com.testerum.common_di.ModuleFactoryContext.shutdown(ModuleFactoryContext.kt:21)
	at com.testerum.common_di.ModuleFactoryContext.close(ModuleFactoryContext.kt:28)
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:61)
	at com.testerum.runner_cmdline.TesterumRunner.main(TesterumRunner.kt:36)
 ```
 
 After a several workaroud by adjusting the nginx config (not works), I assume this issue is related to the Apache server, cmiiw.
 
Is there any workaround to edit the apache config? Thank you

**Comment by muhammad-asn** [comment]
Sorry, I closed this issue
In my environment, I just need to adjust the heap size flags. Thank you.
